### ISSUE TITLE
Find Home Page design

### ISSUE THREAD

**Issue by beSaif** [jumainahkhan/One-Percent#3]

**Comment by beSaif** [comment]
![Image](https://user-images.githubusercontent.com/22230219/197725547-860eeacc-fb2d-40a9-b12e-3ed084c86f19.png)

**Comment by beSaif** [comment]
![Image](https://user-images.githubusercontent.com/22230219/197726457-78123c19-f5dc-450d-ba71-2343dc3242a1.png)

**Comment by beSaif** [comment]
![Image](https://user-images.githubusercontent.com/22230219/197727114-65d6d26a-890b-4c85-8459-da23304575ff.png)

**Comment by jumainahkhan** [comment]
![a881b9a886bc7d6c64d68bc9426d24d7.jpg](https://user-images.githubusercontent.com/110286289/197926676-ee32e30f-cb4a-4957-859a-c591ecbe3163.jpg)

**Comment by jumainahkhan** [comment]
![Momonyetan App Design - To Do List 🤘](https://user-images.githubusercontent.com/110286289/197994035-294a1776-b636-4697-9687-7561024e8e41.png)

**Comment by jumainahkhan** [comment]
![Habit tracker_png by Hafid Fachrudin](https://user-images.githubusercontent.com/110286289/197994381-7bb2036c-feed-428b-a718-8b33ddff5c23.png)
